import { Layout } from "@/components/layout/Layout";

const TermsOfService = () => {
  const lastUpdated = "December 25, 2025";

  return (
    <Layout>
      <div className="min-h-screen bg-background py-16">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-4xl font-bold text-foreground mb-2">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last Updated: {lastUpdated}</p>

          <div className="prose prose-lg dark:prose-invert max-w-none space-y-8">
            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">1. Agreement to Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," 
                or "your") and DomForgeAI ("Company," "we," "us," or "our") governing your access to and use of the 
                DomForgeAI website, platform, and all related services (collectively, the "Service"). By accessing or 
                using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms. 
                If you do not agree to these Terms, you must not access or use the Service. We reserve the right to 
                modify these Terms at any time, and your continued use of the Service constitutes acceptance of such 
                modifications.
              </p>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground leading-relaxed">
                DomForgeAI is an AI-powered platform that generates system architecture packages and microservice 
                implementations based on user-provided business requirements. The Service includes, but is not limited 
                to, domain analysis, architecture generation, code scaffolding, database schema design, and API 
                specification creation. The output generated by the Service is provided as a starting point and 
                requires professional review, customization, and validation before deployment in any production environment.
              </p>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">3. User Accounts and Registration</h2>
              <div className="text-muted-foreground leading-relaxed space-y-4">
                <p>
                  To access certain features of the Service, you must create an account. By creating an account, you agree to:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Provide accurate, current, and complete information during registration</li>
                  <li>Maintain and promptly update your account information</li>
                  <li>Maintain the security and confidentiality of your login credentials</li>
                  <li>Accept responsibility for all activities that occur under your account</li>
                  <li>Notify us immediately of any unauthorized use of your account</li>
                </ul>
                <p>
                  We reserve the right to suspend or terminate your account at our sole discretion, without prior 
                  notice, for any reason, including but not limited to violation of these Terms.
                </p>
              </div>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">4. Subscription and Payment Terms</h2>
              <div className="text-muted-foreground leading-relaxed space-y-4">
                <p>
                  The Service offers various subscription plans with different credit allocations and features. By 
                  subscribing to a paid plan, you agree to the following:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>All fees are quoted in the applicable currency and are non-refundable unless otherwise stated</li>
                  <li>Subscriptions automatically renew unless cancelled before the renewal date</li>
                  <li>You authorize us to charge your payment method for recurring subscription fees</li>
                  <li>Credits expire according to the terms of your subscription plan and do not carry over</li>
                  <li>We reserve the right to modify pricing with reasonable notice to subscribers</li>
                </ul>
                <p>
                  Failure to pay applicable fees may result in suspension or termination of your access to the Service.
                </p>
              </div>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">5. Acceptable Use Policy</h2>
              <div className="text-muted-foreground leading-relaxed space-y-4">
                <p>You agree not to use the Service to:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Violate any applicable laws, regulations, or third-party rights</li>
                  <li>Generate content that is illegal, harmful, threatening, abusive, or otherwise objectionable</li>
                  <li>Attempt to gain unauthorized access to any portion of the Service or related systems</li>
                  <li>Interfere with or disrupt the integrity or performance of the Service</li>
                  <li>Use automated means to access the Service without our express permission</li>
                  <li>Reverse engineer, decompile, or disassemble any aspect of the Service</li>
                  <li>Resell, sublicense, or redistribute the Service without authorization</li>
                  <li>Use the Service to develop competing products or services</li>
                </ul>
              </div>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">6. Intellectual Property Rights</h2>
              <div className="text-muted-foreground leading-relaxed space-y-4">
                <div>
                  <h3 className="text-lg font-medium text-foreground mb-2">6.1 Our Intellectual Property</h3>
                  <p>
                    The Service, including its original content, features, functionality, and underlying technology, 
                    is and will remain the exclusive property of DomForgeAI and its licensors. The Service is protected 
                    by copyright, trademark, and other intellectual property laws. Our trademarks and trade dress may 
                    not be used without our prior written consent.
                  </p>
                </div>
                <div>
                  <h3 className="text-lg font-medium text-foreground mb-2">6.2 Generated Output</h3>
                  <p>
                    Subject to your compliance with these Terms and payment of applicable fees, you retain ownership 
                    of the output generated by the Service based on your inputs. However, you acknowledge that similar 
                    outputs may be generated for other users based on similar inputs, and we make no claims of exclusivity.
                  </p>
                </div>
                <div>
                  <h3 className="text-lg font-medium text-foreground mb-2">6.3 User Content</h3>
                  <p>
                    You retain ownership of any content, data, or information you provide to the Service. By using 
                    the Service, you grant us a non-exclusive, worldwide, royalty-free license to use, process, and 
                    analyze your inputs solely for the purpose of providing and improving the Service.
                  </p>
                </div>
              </div>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">7. Disclaimer of Warranties</h2>
              <div className="text-muted-foreground leading-relaxed space-y-4">
                <p className="uppercase font-semibold">
                  THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, 
                  WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE 
                  LAW, WE EXPRESSLY DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT</li>
                  <li>WARRANTIES THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR VIRUS-FREE</li>
                  <li>WARRANTIES REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF ANY GENERATED OUTPUT</li>
                  <li>WARRANTIES THAT THE GENERATED CODE WILL BE SUITABLE FOR PRODUCTION USE WITHOUT MODIFICATION</li>
                  <li>WARRANTIES THAT THE SERVICE WILL MEET YOUR SPECIFIC REQUIREMENTS OR EXPECTATIONS</li>
                </ul>
                <p>
                  YOU ACKNOWLEDGE AND AGREE THAT THE AI-GENERATED OUTPUT IS PROVIDED AS A STARTING POINT AND REQUIRES 
                  PROFESSIONAL REVIEW, TESTING, AND VALIDATION. YOU ASSUME ALL RESPONSIBILITY FOR THE USE, DEPLOYMENT, 
                  AND CONSEQUENCES OF ANY GENERATED OUTPUT.
                </p>
              </div>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">8. Limitation of Liability</h2>
              <div className="text-muted-foreground leading-relaxed space-y-4">
                <p className="uppercase font-semibold">
                  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL DOMFORGEAI, ITS DIRECTORS, 
                  OFFICERS, EMPLOYEES, AGENTS, PARTNERS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, 
                  INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>DAMAGES FOR LOSS OF PROFITS, REVENUE, GOODWILL, OR DATA</li>
                  <li>DAMAGES ARISING FROM BUSINESS INTERRUPTION OR SYSTEM FAILURES</li>
                  <li>DAMAGES RESULTING FROM THE USE OR INABILITY TO USE THE SERVICE</li>
                  <li>DAMAGES ARISING FROM ERRORS, BUGS, OR INACCURACIES IN GENERATED OUTPUT</li>
                  <li>DAMAGES RESULTING FROM UNAUTHORIZED ACCESS TO YOUR ACCOUNT OR DATA</li>
                  <li>DAMAGES ARISING FROM THE DEPLOYMENT OF GENERATED CODE IN PRODUCTION ENVIRONMENTS</li>
                </ul>
                <p className="uppercase font-semibold">
                  IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATED TO THE SERVICE 
                  EXCEED THE AMOUNT PAID BY YOU TO US DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT 
                  GIVING RISE TO THE CLAIM, OR ONE HUNDRED DOLLARS ($100), WHICHEVER IS GREATER.
                </p>
              </div>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">9. Indemnification</h2>
              <p className="text-muted-foreground leading-relaxed">
                You agree to defend, indemnify, and hold harmless DomForgeAI and its officers, directors, employees, 
                contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, 
                liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable 
                attorneys' fees) arising out of or relating to: (a) your violation of these Terms; (b) your use of 
                the Service; (c) your deployment or use of any generated output; (d) your violation of any third-party 
                rights; or (e) any content or data you provide to the Service.
              </p>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">10. Service Modifications and Availability</h2>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to modify, suspend, or discontinue the Service (or any part thereof) at any time, 
                with or without notice. We shall not be liable to you or any third party for any modification, 
                suspension, or discontinuation of the Service. We do not guarantee that the Service will be available 
                at all times. We may experience hardware, software, or other problems, or need to perform maintenance, 
                resulting in interruptions, delays, or errors.
              </p>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">11. Third-Party Services and Links</h2>
              <p className="text-muted-foreground leading-relaxed">
                The Service may contain links to or integrate with third-party websites, services, or applications. 
                We have no control over and assume no responsibility for the content, privacy policies, or practices 
                of any third-party services. You acknowledge and agree that we shall not be responsible or liable for 
                any damage or loss caused by or in connection with the use of any third-party services. We encourage 
                you to review the terms and policies of any third-party services you access.
              </p>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">12. Governing Law and Dispute Resolution</h2>
              <div className="text-muted-foreground leading-relaxed space-y-4">
                <p>
                  These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in 
                  which DomForgeAI is registered, without regard to its conflict of law provisions.
                </p>
                <p>
                  Any dispute arising out of or relating to these Terms or the Service shall first be attempted to be 
                  resolved through good-faith negotiations. If such negotiations fail, the dispute shall be resolved 
                  through binding arbitration in accordance with the rules of a recognized arbitration institution. 
                  The arbitration shall be conducted in the English language, and the arbitrator's decision shall be 
                  final and binding.
                </p>
                <p>
                  YOU AGREE TO WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION 
                  AGAINST DOMFORGEAI.
                </p>
              </div>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">13. Termination</h2>
              <div className="text-muted-foreground leading-relaxed space-y-4">
                <p>
                  We may terminate or suspend your account and access to the Service immediately, without prior notice 
                  or liability, for any reason whatsoever, including without limitation if you breach these Terms.
                </p>
                <p>
                  Upon termination, your right to use the Service will immediately cease. If you wish to terminate 
                  your account, you may simply discontinue using the Service or contact us to request account deletion.
                </p>
                <p>
                  All provisions of these Terms which by their nature should survive termination shall survive, 
                  including ownership provisions, warranty disclaimers, indemnification, and limitations of liability.
                </p>
              </div>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">14. Severability</h2>
              <p className="text-muted-foreground leading-relaxed">
                If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court of 
                competent jurisdiction, such invalidity, illegality, or unenforceability shall not affect the 
                remaining provisions of these Terms. The remaining provisions shall continue in full force and 
                effect, and the invalid or unenforceable provision shall be modified to the minimum extent necessary 
                to make it valid and enforceable while preserving its original intent.
              </p>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">15. Entire Agreement</h2>
              <p className="text-muted-foreground leading-relaxed">
                These Terms, together with our Privacy Policy and any other legal notices or agreements published by 
                us on the Service, constitute the entire agreement between you and DomForgeAI regarding your use of 
                the Service. These Terms supersede all prior and contemporaneous understandings, agreements, 
                representations, and warranties, both written and oral, regarding the Service.
              </p>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">16. Waiver</h2>
              <p className="text-muted-foreground leading-relaxed">
                No waiver of any term or condition of these Terms shall be deemed a further or continuing waiver of 
                such term or condition or a waiver of any other term or condition. Our failure to assert any right or 
                provision under these Terms shall not constitute a waiver of such right or provision.
              </p>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">17. Contact Information</h2>
              <p className="text-muted-foreground leading-relaxed">
                If you have any questions about these Terms of Service, please contact us at:
              </p>
              <div className="mt-4 text-foreground">
                <p><strong>DomForgeAI</strong></p>
                <p className="text-muted-foreground">Email: legal@domforgeai.com</p>
              </div>
            </section>

            <section className="bg-card border border-border rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-foreground mb-4">18. Acknowledgment</h2>
              <p className="text-muted-foreground leading-relaxed">
                BY USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE, UNDERSTAND THEM, 
                AND AGREE TO BE BOUND BY THEM. IF YOU DO NOT AGREE TO THESE TERMS, YOU ARE NOT AUTHORIZED TO USE 
                THE SERVICE. These Terms were last updated on the date indicated at the top of this page.
              </p>
            </section>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default TermsOfService;
